# Generated by Django 5.0.7 on 2024-07-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='duration',
            field=models.CharField(choices=[('1M', '1 minute'), ('5M', '5 minutes'), ('10M', '10 minutes')], default='5M', max_length=3),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
