# Generated by Django 5.0.7 on 2024-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
    ]
