# Generated by Django 5.0.7 on 2024-07-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_poll_duration_alter_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_open',
        ),
    ]
