# Generated by Django 5.0.7 on 2024-07-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240715_2138'),
    ]

    operations = [
    ]
