# Generated by Django 5.0.7 on 2024-07-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_poll_is_open'),
    ]

    operations = [
    ]
