# Generated by Django 5.0.7 on 2024-07-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240715_2139'),
    ]

    operations = [
    ]
