# Generated by Django 5.0.7 on 2024-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240716_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='duration',
            field=models.CharField(choices=[('EM', 'E minute'), ('1M', '1 minute'), ('5M', '5 minutes'), ('10M', '10 minutes')], default='5M', max_length=3),
        ),
    ]
