# Generated by Django 5.0.7 on 2024-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_poll_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes_changable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_visible',
            field=models.BooleanField(default=True),
        ),
    ]
