# Generated by Django 5.0.7 on 2024-07-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_poll_votes_changable_poll_votes_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
